PARTICIPANTS: use this file for creating the remove book from catalog diagram in mastery task 01
RemoveBookFromCatalog
@startuml

RemoveBookFromCatalogActivity->RemoveBookFromCatalogResponse

CatalogDao
RemoveBookFromCatalogResponse
throws BookNotFoundException

RemoveBookFromCatalog
execute
removeBookFromCatalog




@enduml